2016-09-25 16:45:37,204 [ERROR][Thread-2:140304599987968] [exception.handle_uncaught_exception django.request:124] -- Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/syn/PycharmProjects/xinhua_vote/vote/views.py", line 13, in show_main_list
    candidates = Candidate.objects.get()
  File "/usr/local/lib/python3.5/dist-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/db/models/query.py", line 389, in get
    (self.model._meta.object_name, num)
vote.models.MultipleObjectsReturned: get() returned more than one Candidate -- it returned 2!
2016-09-25 16:45:38,237 [ERROR][Thread-3:140304591595264] [exception.handle_uncaught_exception django.request:124] -- Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/syn/PycharmProjects/xinhua_vote/vote/views.py", line 13, in show_main_list
    candidates = Candidate.objects.get()
  File "/usr/local/lib/python3.5/dist-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/db/models/query.py", line 389, in get
    (self.model._meta.object_name, num)
vote.models.MultipleObjectsReturned: get() returned more than one Candidate -- it returned 2!
2016-09-25 16:46:18,079 [ERROR][Thread-2:139904851519232] [exception.handle_uncaught_exception django.request:124] -- Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/syn/PycharmProjects/xinhua_vote/vote/views.py", line 14, in show_main_list
    return render_to_response("list.html", candidates)
  File "/usr/local/lib/python3.5/dist-packages/django/shortcuts.py", line 21, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "/usr/local/lib/python3.5/dist-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/usr/local/lib/python3.5/dist-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: list.html
2016-09-25 16:46:18,817 [ERROR][Thread-3:139904843126528] [exception.handle_uncaught_exception django.request:124] -- Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/syn/PycharmProjects/xinhua_vote/vote/views.py", line 14, in show_main_list
    return render_to_response("list.html", candidates)
  File "/usr/local/lib/python3.5/dist-packages/django/shortcuts.py", line 21, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "/usr/local/lib/python3.5/dist-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/usr/local/lib/python3.5/dist-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: list.html
2016-09-25 16:50:06,897 [ERROR][Thread-2:140395962369792] [exception.handle_uncaught_exception django.request:124] -- Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/syn/PycharmProjects/xinhua_vote/vote/views.py", line 14, in show_main_list
    return render_to_response("vote/list.html", candidates)
  File "/usr/local/lib/python3.5/dist-packages/django/shortcuts.py", line 21, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "/usr/local/lib/python3.5/dist-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/usr/local/lib/python3.5/dist-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: vote/list.html
2016-09-25 16:50:07,633 [ERROR][Thread-3:140395953977088] [exception.handle_uncaught_exception django.request:124] -- Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/syn/PycharmProjects/xinhua_vote/vote/views.py", line 14, in show_main_list
    return render_to_response("vote/list.html", candidates)
  File "/usr/local/lib/python3.5/dist-packages/django/shortcuts.py", line 21, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "/usr/local/lib/python3.5/dist-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/usr/local/lib/python3.5/dist-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: vote/list.html
2016-09-25 16:55:01,930 [ERROR][Thread-7:140572303075072] [exception.handle_uncaught_exception django.request:124] -- Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/syn/PycharmProjects/xinhua_vote/vote/views.py", line 21, in show_main_list
    return render_to_response("vote/list.html", candidates)
  File "/usr/local/lib/python3.5/dist-packages/django/shortcuts.py", line 21, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "/usr/local/lib/python3.5/dist-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/usr/local/lib/python3.5/dist-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: vote/list.html
2016-09-25 16:58:38,201 [ERROR][Thread-2:139800255293184] [exception.handle_uncaught_exception django.request:124] -- Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/syn/PycharmProjects/xinhua_vote/vote/views.py", line 21, in show_main_list
    return render_to_response("vote/list.html", {candidates})
TypeError: unhashable type: 'list'
2016-09-25 16:58:38,899 [ERROR][Thread-3:139800178849536] [exception.handle_uncaught_exception django.request:124] -- Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/syn/PycharmProjects/xinhua_vote/vote/views.py", line 21, in show_main_list
    return render_to_response("vote/list.html", {candidates})
TypeError: unhashable type: 'list'
2016-09-25 17:11:33,111 [ERROR][Thread-2:139767427553024] [exception.handle_uncaught_exception django.request:124] -- Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 510, in parse
    compile_func = self.tags[command]
KeyError: 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/syn/PycharmProjects/xinhua_vote/vote/views.py", line 21, in show_main_list
    return render_to_response("vote/list.html", {"candidates": candidates})
  File "/usr/local/lib/python3.5/dist-packages/django/shortcuts.py", line 21, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "/usr/local/lib/python3.5/dist-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/usr/local/lib/python3.5/dist-packages/django/template/loader.py", line 21, in get_template
    return engine.get_template(template_name)
  File "/usr/local/lib/python3.5/dist-packages/django/template/backends/django.py", line 39, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/usr/local/lib/python3.5/dist-packages/django/template/engine.py", line 160, in get_template
    template, origin = self.find_template(template_name)
  File "/usr/local/lib/python3.5/dist-packages/django/template/engine.py", line 134, in find_template
    name, template_dirs=dirs, skip=skip,
  File "/usr/local/lib/python3.5/dist-packages/django/template/loaders/base.py", line 44, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 191, in __init__
    self.nodelist = self.compile_nodelist()
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 233, in compile_nodelist
    return parser.parse()
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 512, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 574, in invalid_block_tag
    "or load this tag?" % (token.lineno, command)
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 7: 'static'. Did you forget to register or load this tag?
2016-09-25 17:11:33,857 [ERROR][Thread-3:139767419160320] [exception.handle_uncaught_exception django.request:124] -- Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 510, in parse
    compile_func = self.tags[command]
KeyError: 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/syn/PycharmProjects/xinhua_vote/vote/views.py", line 21, in show_main_list
    return render_to_response("vote/list.html", {"candidates": candidates})
  File "/usr/local/lib/python3.5/dist-packages/django/shortcuts.py", line 21, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "/usr/local/lib/python3.5/dist-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/usr/local/lib/python3.5/dist-packages/django/template/loader.py", line 21, in get_template
    return engine.get_template(template_name)
  File "/usr/local/lib/python3.5/dist-packages/django/template/backends/django.py", line 39, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/usr/local/lib/python3.5/dist-packages/django/template/engine.py", line 160, in get_template
    template, origin = self.find_template(template_name)
  File "/usr/local/lib/python3.5/dist-packages/django/template/engine.py", line 134, in find_template
    name, template_dirs=dirs, skip=skip,
  File "/usr/local/lib/python3.5/dist-packages/django/template/loaders/base.py", line 44, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 191, in __init__
    self.nodelist = self.compile_nodelist()
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 233, in compile_nodelist
    return parser.parse()
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 512, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 574, in invalid_block_tag
    "or load this tag?" % (token.lineno, command)
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 7: 'static'. Did you forget to register or load this tag?
2016-09-25 17:33:23,358 [ERROR][Thread-27:139846744008448] [exception.handle_uncaught_exception django.request:124] -- Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/syn/PycharmProjects/xinhua_vote/vote/views.py", line 21, in show_main_list
    return render_to_response("vote/list.html", {"candidates": candidates})
  File "/usr/local/lib/python3.5/dist-packages/django/shortcuts.py", line 21, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "/usr/local/lib/python3.5/dist-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/usr/local/lib/python3.5/dist-packages/django/template/loader.py", line 21, in get_template
    return engine.get_template(template_name)
  File "/usr/local/lib/python3.5/dist-packages/django/template/backends/django.py", line 39, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/usr/local/lib/python3.5/dist-packages/django/template/engine.py", line 160, in get_template
    template, origin = self.find_template(template_name)
  File "/usr/local/lib/python3.5/dist-packages/django/template/engine.py", line 134, in find_template
    name, template_dirs=dirs, skip=skip,
  File "/usr/local/lib/python3.5/dist-packages/django/template/loaders/base.py", line 44, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 191, in __init__
    self.nodelist = self.compile_nodelist()
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 233, in compile_nodelist
    return parser.parse()
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/usr/local/lib/python3.5/dist-packages/django/template/defaulttags.py", line 803, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/usr/local/lib/python3.5/dist-packages/django/templatetags/static.py", line 155, in do_static
    return StaticNode.handle_token(parser, token)
  File "/usr/local/lib/python3.5/dist-packages/django/templatetags/static.py", line 129, in handle_token
    path = parser.compile_filter(bits[1])
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 603, in compile_filter
    return FilterExpression(token, self)
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 703, in __init__
    "from '%s'" % (token[upto:], token))
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '{{' from '{{'
2016-09-25 17:33:24,189 [ERROR][Thread-28:139846752401152] [exception.handle_uncaught_exception django.request:124] -- Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/syn/PycharmProjects/xinhua_vote/vote/views.py", line 21, in show_main_list
    return render_to_response("vote/list.html", {"candidates": candidates})
  File "/usr/local/lib/python3.5/dist-packages/django/shortcuts.py", line 21, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "/usr/local/lib/python3.5/dist-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/usr/local/lib/python3.5/dist-packages/django/template/loader.py", line 21, in get_template
    return engine.get_template(template_name)
  File "/usr/local/lib/python3.5/dist-packages/django/template/backends/django.py", line 39, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/usr/local/lib/python3.5/dist-packages/django/template/engine.py", line 160, in get_template
    template, origin = self.find_template(template_name)
  File "/usr/local/lib/python3.5/dist-packages/django/template/engine.py", line 134, in find_template
    name, template_dirs=dirs, skip=skip,
  File "/usr/local/lib/python3.5/dist-packages/django/template/loaders/base.py", line 44, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 191, in __init__
    self.nodelist = self.compile_nodelist()
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 233, in compile_nodelist
    return parser.parse()
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/usr/local/lib/python3.5/dist-packages/django/template/defaulttags.py", line 803, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/usr/local/lib/python3.5/dist-packages/django/templatetags/static.py", line 155, in do_static
    return StaticNode.handle_token(parser, token)
  File "/usr/local/lib/python3.5/dist-packages/django/templatetags/static.py", line 129, in handle_token
    path = parser.compile_filter(bits[1])
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 603, in compile_filter
    return FilterExpression(token, self)
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 703, in __init__
    "from '%s'" % (token[upto:], token))
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '{{' from '{{'
2016-09-25 17:33:26,870 [ERROR][Thread-29:139847101224704] [exception.handle_uncaught_exception django.request:124] -- Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/syn/PycharmProjects/xinhua_vote/vote/views.py", line 21, in show_main_list
    return render_to_response("vote/list.html", {"candidates": candidates})
  File "/usr/local/lib/python3.5/dist-packages/django/shortcuts.py", line 21, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "/usr/local/lib/python3.5/dist-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/usr/local/lib/python3.5/dist-packages/django/template/loader.py", line 21, in get_template
    return engine.get_template(template_name)
  File "/usr/local/lib/python3.5/dist-packages/django/template/backends/django.py", line 39, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/usr/local/lib/python3.5/dist-packages/django/template/engine.py", line 160, in get_template
    template, origin = self.find_template(template_name)
  File "/usr/local/lib/python3.5/dist-packages/django/template/engine.py", line 134, in find_template
    name, template_dirs=dirs, skip=skip,
  File "/usr/local/lib/python3.5/dist-packages/django/template/loaders/base.py", line 44, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 191, in __init__
    self.nodelist = self.compile_nodelist()
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 233, in compile_nodelist
    return parser.parse()
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/usr/local/lib/python3.5/dist-packages/django/template/defaulttags.py", line 803, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/usr/local/lib/python3.5/dist-packages/django/templatetags/static.py", line 155, in do_static
    return StaticNode.handle_token(parser, token)
  File "/usr/local/lib/python3.5/dist-packages/django/templatetags/static.py", line 129, in handle_token
    path = parser.compile_filter(bits[1])
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 603, in compile_filter
    return FilterExpression(token, self)
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 703, in __init__
    "from '%s'" % (token[upto:], token))
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '{{' from '{{'
2016-09-25 17:33:27,731 [ERROR][Thread-30:139847118010112] [exception.handle_uncaught_exception django.request:124] -- Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/syn/PycharmProjects/xinhua_vote/vote/views.py", line 21, in show_main_list
    return render_to_response("vote/list.html", {"candidates": candidates})
  File "/usr/local/lib/python3.5/dist-packages/django/shortcuts.py", line 21, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "/usr/local/lib/python3.5/dist-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/usr/local/lib/python3.5/dist-packages/django/template/loader.py", line 21, in get_template
    return engine.get_template(template_name)
  File "/usr/local/lib/python3.5/dist-packages/django/template/backends/django.py", line 39, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/usr/local/lib/python3.5/dist-packages/django/template/engine.py", line 160, in get_template
    template, origin = self.find_template(template_name)
  File "/usr/local/lib/python3.5/dist-packages/django/template/engine.py", line 134, in find_template
    name, template_dirs=dirs, skip=skip,
  File "/usr/local/lib/python3.5/dist-packages/django/template/loaders/base.py", line 44, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 191, in __init__
    self.nodelist = self.compile_nodelist()
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 233, in compile_nodelist
    return parser.parse()
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/usr/local/lib/python3.5/dist-packages/django/template/defaulttags.py", line 803, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/usr/local/lib/python3.5/dist-packages/django/templatetags/static.py", line 155, in do_static
    return StaticNode.handle_token(parser, token)
  File "/usr/local/lib/python3.5/dist-packages/django/templatetags/static.py", line 129, in handle_token
    path = parser.compile_filter(bits[1])
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 603, in compile_filter
    return FilterExpression(token, self)
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 703, in __init__
    "from '%s'" % (token[upto:], token))
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '{{' from '{{'
2016-09-25 17:34:48,286 [ERROR][Thread-53:139847109617408] [exception.handle_uncaught_exception django.request:124] -- Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/syn/PycharmProjects/xinhua_vote/vote/views.py", line 21, in show_main_list
    return render_to_response("vote/list.html", {"candidates": candidates})
  File "/usr/local/lib/python3.5/dist-packages/django/shortcuts.py", line 21, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "/usr/local/lib/python3.5/dist-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/usr/local/lib/python3.5/dist-packages/django/template/loader.py", line 21, in get_template
    return engine.get_template(template_name)
  File "/usr/local/lib/python3.5/dist-packages/django/template/backends/django.py", line 39, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/usr/local/lib/python3.5/dist-packages/django/template/engine.py", line 160, in get_template
    template, origin = self.find_template(template_name)
  File "/usr/local/lib/python3.5/dist-packages/django/template/engine.py", line 134, in find_template
    name, template_dirs=dirs, skip=skip,
  File "/usr/local/lib/python3.5/dist-packages/django/template/loaders/base.py", line 44, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 191, in __init__
    self.nodelist = self.compile_nodelist()
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 233, in compile_nodelist
    return parser.parse()
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/usr/local/lib/python3.5/dist-packages/django/template/defaulttags.py", line 803, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/usr/local/lib/python3.5/dist-packages/django/templatetags/static.py", line 155, in do_static
    return StaticNode.handle_token(parser, token)
  File "/usr/local/lib/python3.5/dist-packages/django/templatetags/static.py", line 129, in handle_token
    path = parser.compile_filter(bits[1])
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 603, in compile_filter
    return FilterExpression(token, self)
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 703, in __init__
    "from '%s'" % (token[upto:], token))
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '{{' from '{{'
2016-09-25 17:34:49,128 [ERROR][Thread-54:139847101224704] [exception.handle_uncaught_exception django.request:124] -- Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/syn/PycharmProjects/xinhua_vote/vote/views.py", line 21, in show_main_list
    return render_to_response("vote/list.html", {"candidates": candidates})
  File "/usr/local/lib/python3.5/dist-packages/django/shortcuts.py", line 21, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "/usr/local/lib/python3.5/dist-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/usr/local/lib/python3.5/dist-packages/django/template/loader.py", line 21, in get_template
    return engine.get_template(template_name)
  File "/usr/local/lib/python3.5/dist-packages/django/template/backends/django.py", line 39, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/usr/local/lib/python3.5/dist-packages/django/template/engine.py", line 160, in get_template
    template, origin = self.find_template(template_name)
  File "/usr/local/lib/python3.5/dist-packages/django/template/engine.py", line 134, in find_template
    name, template_dirs=dirs, skip=skip,
  File "/usr/local/lib/python3.5/dist-packages/django/template/loaders/base.py", line 44, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 191, in __init__
    self.nodelist = self.compile_nodelist()
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 233, in compile_nodelist
    return parser.parse()
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/usr/local/lib/python3.5/dist-packages/django/template/defaulttags.py", line 803, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/usr/local/lib/python3.5/dist-packages/django/templatetags/static.py", line 155, in do_static
    return StaticNode.handle_token(parser, token)
  File "/usr/local/lib/python3.5/dist-packages/django/templatetags/static.py", line 129, in handle_token
    path = parser.compile_filter(bits[1])
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 603, in compile_filter
    return FilterExpression(token, self)
  File "/usr/local/lib/python3.5/dist-packages/django/template/base.py", line 703, in __init__
    "from '%s'" % (token[upto:], token))
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '{{' from '{{'
2016-09-25 21:28:09,484 [WARNING][Thread-5:140027047315200] [base.get_response django.request:152] -- Not Found: /favicon.ico
2016-09-25 21:29:16,027 [WARNING][Thread-28:140027064100608] [base.get_response django.request:152] -- Not Found: /
2016-09-25 21:29:23,504 [WARNING][Thread-31:140027027818240] [base.get_response django.request:152] -- Not Found: /
2016-09-25 21:30:56,948 [WARNING][Thread-26:140705527748352] [base.get_response django.request:152] -- Not Found: /
2016-09-25 21:32:37,025 [ERROR][Thread-4:140371782313728] [exception.handle_uncaught_exception django.request:124] -- Internal Server Error: /content/1/
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/syn/PycharmProjects/xinhua_vote/vote/views.py", line 32, in show_contents
    "lines": main_candidate.description.spllit('\n'),
AttributeError: 'str' object has no attribute 'spllit'
2016-09-25 21:32:50,755 [WARNING][Thread-9:140173264373504] [base.get_response django.request:152] -- Not Found: /
2016-09-25 21:34:02,472 [WARNING][Thread-14:140445665441536] [base.get_response django.request:152] -- Not Found: /
2016-09-26 09:11:38,875 [WARNING][Thread-2:139962270848768] [base.get_response django.request:152] -- Not Found: /
2016-09-26 09:11:42,394 [WARNING][Thread-3:139962262456064] [base.get_response django.request:152] -- Not Found: /favicon.ico
2016-09-26 09:11:48,659 [WARNING][Thread-19:139962270848768] [base.get_response django.request:152] -- Not Found: /
2016-09-26 09:11:48,848 [WARNING][Thread-20:139962037036800] [base.get_response django.request:152] -- Not Found: /
2016-09-26 10:40:02,584 [ERROR][Thread-17:139941720831744] [exception.handle_uncaught_exception django.request:124] -- Internal Server Error: /charts/
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/syn/PycharmProjects/xinhua_vote/vote/views.py", line 59, in show_charts
    "bar_style": "width: " + str((one_candidate.voted * 100) / (all_vote * 100) / 100) + "%",
TypeError: unsupported operand type(s) for *: 'dict' and 'int'
2016-09-26 10:50:48,449 [ERROR][Thread-7:139625945372416] [exception.handle_uncaught_exception django.request:124] -- Internal Server Error: /charts/
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/syn/PycharmProjects/xinhua_vote/vote/views.py", line 54, in show_charts
    tmp_bar_style = one_candidate.voted * 100 / all_vote.voted__sum
AttributeError: 'dict' object has no attribute 'voted__sum'
2016-09-26 10:51:42,554 [ERROR][Thread-2:140300923561728] [exception.handle_uncaught_exception django.request:124] -- Internal Server Error: /charts/
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 198, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view vote.views.show_charts didn't return an HttpResponse object. It returned None instead.
2016-09-26 14:11:13,071 [WARNING][Thread-16:139931502503680] [base.get_response django.request:152] -- Not Found: /favicon.ico
2016-09-26 14:11:22,404 [WARNING][Thread-18:139931502503680] [base.get_response django.request:152] -- Not Found: /favicon.ico
2016-09-26 14:11:38,241 [WARNING][Thread-24:139931726370560] [base.get_response django.request:152] -- Not Found: /favicon.ico
2016-09-26 14:12:06,089 [WARNING][Thread-41:139931510896384] [base.get_response django.request:152] -- Not Found: /favicon.ico
2016-09-26 14:13:10,274 [WARNING][Thread-49:139931510896384] [base.get_response django.request:152] -- Not Found: /favicon.ico
2016-09-26 14:14:59,353 [WARNING][Thread-99:139931510896384] [base.get_response django.request:152] -- Not Found: /favicon.ico
2016-09-26 14:14:59,389 [WARNING][Thread-100:139931510896384] [base.get_response django.request:152] -- Not Found: /favicon.ico
2016-09-26 14:16:00,270 [WARNING][Thread-102:139931494110976] [base.get_response django.request:152] -- Not Found: /favicon.ico
2016-09-26 14:16:00,373 [WARNING][Thread-103:139931494110976] [base.get_response django.request:152] -- Not Found: /favicon.ico
2016-09-26 14:16:23,758 [WARNING][Thread-108:139931494110976] [base.get_response django.request:152] -- Not Found: /favicon.ico
2016-09-26 14:23:20,355 [WARNING][Thread-2:140004606588672] [base.get_response django.request:152] -- Not Found: /do_vote/1/
2016-09-26 14:23:31,261 [WARNING][Thread-3:140004606588672] [base.get_response django.request:152] -- Not Found: /do_vote/3/
2016-09-26 14:23:44,275 [WARNING][Thread-5:140004606588672] [base.get_response django.request:152] -- Not Found: /do_vote/list/1/
2016-09-26 14:24:34,665 [WARNING][Thread-15:140593934100224] [base.get_response django.request:152] -- Not Found: /do_vote/list/1/
